# Generated by Django 2.2.2 on 2019-07-03 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
