# Generated by Django 2.2.2 on 2019-07-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_user_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_added',
            new_name='date_updated',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user_created',
        ),
    ]
