# Generated by Django 2.2.2 on 2019-07-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.CharField(max_length=10),
        ),
    ]
